spring:
  #数据库驱动配置信息 
  datasource:
  #sqlserver数据源
  #  url: jdbc:sqlserver://localhost:52409;DatabaseName=sino_test
  #  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #  username: saoa  
  #  password: saoa123456
    
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong 
    driverClassName : com.mysql.jdbc.Driver
    username: root  
    password: root

server:
  #端口号
  port: 8180
  mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
  #session最大超时时间（默认30分钟）
  session: 60
  tomcat:
    #tomcat的uri编码
    uri-encoding: utf-8  
    
    
  