server:
  #端口号
  port: 8180
  mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
  #session最大超时时间（默认30分钟）
  session: 60
  tomcat:
    #tomcat的uri编码
    uri-encoding: utf-8
  

  